### ISSUE TITLE
A D D  T H E  S L N  F I L E

### ISSUE THREAD

**Issue by broimsuperman** [EchoHackCmd/Bolt#1]
Add the SLN file so I can contribute/pull request smh, don't feel like manually doing everything 🙄

**Comment by EchoHackCmd** [comment]
Just open the project with `Visual Studio Code`, not `Visual Studio`

**Comment by broimsuperman** [comment]
> Just open the project with `Visual Studio Code`, not `Visual Studio`

Then I can't check for errors and make sure the module actually works!

**Comment by EchoHackCmd** [comment]
I don't get what you're trying to do and you should be able to check for errors

**Comment by broimsuperman** [comment]
I am trying to add some new modules, I'd need to compile the project to ensure they work silly.

**Comment by EchoHackCmd** [comment]
Make sure CMake is installed
