### ISSUE TITLE
how do i build this

### ISSUE THREAD

**Issue by zeaxgg** [EchoHackCmd/Bolt#3]

**Comment by CXCubeHD** [comment]
Just use CMake?

**Comment by zeaxgg** [comment]
> Just use CMake?

i tried and it didn't work

**Comment by CXCubeHD** [comment]
> i tried and it didn't work

well any more details would be helpful I guess?

**Comment by EchoHackCmd** [comment]
Use Visual Studio Code, go to the package manager and make sure CMake tools is installed and from there it's the most easiest thing in the world

**Comment by CXCubeHD** [comment]
I swear to god these people are so dumb 🤦🏻‍♂️

**Comment by EchoHackCmd** [comment]
CXCube, mind adding me on Discord?

**Comment by broimsuperman** [comment]
China
